name: 'Deploy to AWS s3'
description: 'Deploy a static website to AWS s3 with docker'
inputs:
  bucket:
    description: 'The name of the s3 bucket'
    required: true
  bucket-region:
    description: 'The region of the s3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder where the static files are located'
    required: true
outputs:
  website-url:
    description: 'The url of the deployed website'

runs:
  using: 'docker'
  image: 'Dockerfile'
